version: '3.8'

services:
  web:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 5001:5000
    env_file:
      - ./app/.flaskenv
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
